version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3200:3200"
    environment:
      - HOST=0.0.0.0 # Pastikan container mendengarkan di semua alamat
      - NODE_ENV=production
      - NEXT_PUBLIC_SOCKET_URL=http://192.168.6.79:3100
      - NEXT_PUBLIC_API_BASE_URL=http://192.168.6.79:3100
    networks:
      - app_network
    stdin_open: true
    tty: true
    restart: always
    command: ["npx", "next", "start", "-p", "3200", "-H", "0.0.0.0"]

networks:
  app_network:
    driver: bridge
